name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push backend image
      run: |
        docker build -t umamas/task-manager-backend:latest -f server/Dockerfile .
        docker push umamas/task-manager-backend:latest
        
    - name: Build and push frontend image
      run: |
        docker build -t umamas/task-manager-frontend:latest .
        docker push umamas/task-manager-frontend:latest
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/mongodb-deployment.yaml
        kubectl apply -f k8s/mongodb-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml